### ISSUE TITLE
Remontar layout do cadastro na web (layout mais próximo do aplicativo)

### ISSUE THREAD

**Issue by marcoamarelo** [itsriodejaneiro/mudamos-web#101]

**Comment by reu** [comment]
Segue a primeira versão das telas. Talvez ainda hajam algumas mudanças cosméticas, mas nada muito impactante.

### Telas superiores a 1024
![plip-final](https://cloud.githubusercontent.com/assets/191614/22156309/e2aab7ca-df19-11e6-9c65-b94446f68472.png)

A sidebar terá 50% do viewport, e os outros 50% serão a descrição da PLIP e o texto completo dela. Vale ressaltar que a ideia é manter o padding fixo em 50 pixels nas duas views.

### Telas inferiores a 1024 (tablets em geral)
O layout nesse caso muda consideravelmente, já que ele
![plip-final-tablet](https://cloud.githubusercontent.com/assets/191614/22156308/e2a98c4c-df19-11e6-9e4f-79d1f7bb7c68.png)

### Dispositivos mobile
Em telas de celulares, a ideia é fazer algo muito semelhante a app
![mobile](https://cloud.githubusercontent.com/assets/191614/22156701/a4a16f76-df1b-11e6-97e5-a8ecfef2092f.png)

**Comment by viniciusvgv** [comment]
Segue o layout aprovado 
[session.pdf](https://github.com/itsriodejaneiro/mudamos-web/files/856239/session.pdf)
