### ISSUE TITLE
Criação do template de confirmação de e-mail

### ISSUE THREAD

**Issue by marcoamarelo** [itsriodejaneiro/mudamos-web#102]
Hoje a mensagem de e-mail está essa coisa linda.

https://www.dropbox.com/s/x4zlpoxi0uezlms/email-confirmacao.png

Precisamos de um template compatível com a nossa proposta visual do aplicativo. O texto é esse e já foi aprovado. Precisamos só fazer a inflexão de gênero em "Prezado" para "Prezada(o)". Sim, o feminino na frente.

Aquele "VALIDE SEU EMAIL" era pra ser um botão.

**Comment by reu** [comment]
O que acham?
![confirmacao](https://cloud.githubusercontent.com/assets/191614/22244052/1e404b34-e211-11e6-8992-02195576954e.png)

**Comment by marcoamarelo** [comment]
Fechado @reu. Você gera o html dele pra podermos passar para o Renato Martins?

**Comment by viniciusvgv** [comment]
Segue o html enviado para o Renato
[signup-mail.zip](https://github.com/itsriodejaneiro/mudamos-web/files/732116/signup-mail.zip)
