### ISSUE TITLE
Criação da página de mensagem de confirmação do e-mail

### ISSUE THREAD

**Issue by marcoamarelo** [itsriodejaneiro/mudamos-web#103]
Após clicar no link de confirmação do e-mail, é chamada uma página que apresenta uma mensagem de sucesso ou de erro. Hoje ela está assim

https://www.dropbox.com/s/n3uanaldavi2odh/mensagem-resposta-link.png

Precisamos montar uma página template. Lembrando que ela não pode conter todos os elementos do mudamos-web, porque quem responderá num primeiro momento é SERVIDOR DE API. Logo, imaginei um box centralizado com a mensagem e embaixo a marca da mudamos com um link para o site principal, ou a petição.

**Comment by reu** [comment]
O que acham de algo assim?
![confirmado](https://cloud.githubusercontent.com/assets/191614/22244028/0d4f228c-e211-11e6-84a7-89876344fe83.png)

**Comment by marcoamarelo** [comment]
Boa @reu uma dúvida, você vinha insistindo no roxo em tudo e agora optou pelo verde, isso é só uma questão mimética? Se sim, tudo bem. O botão continuar deverá levar a pessoa a petição em que ela estava assinando. Acho que hoje essa info não trafega pra api, então ela deverá fixar o link por enquanto até tornarmos isso dinâmico.

**Comment by reu** [comment]
Então @marcoamarelo, eu to usando verde mais por conta de ser casos de sucesso e tudo mais. O roxo eu só usei para poder ter alguma cor nas telas para fazer os layouts, mas ele poderá ser customizado por ciclos.

Quanto ao link, imagino que quem irá fornecer a URL de retorno terá que ser o servidor da API, independentemente se será hardcoded ou não (por ora, pelo que eu estou entendo, poderia ser configurado com uma variável de ambiente, já que só teremos um ciclo rodando).

**Comment by viniciusvgv** [comment]
Segue o html da página
[signed_up_page.zip](https://github.com/itsriodejaneiro/mudamos-web/files/738852/signed_up_page.zip)

**Comment by viniciusvgv** [comment]
Ilustração para a página de erro: 
![drawing_error](https://cloud.githubusercontent.com/assets/7226070/22425821/116705e2-e6e4-11e6-8d00-c168f5f1c8d6.png)
