### ISSUE TITLE
Criação layot do botão embed

### ISSUE THREAD

**Issue by marcoamarelo** [itsriodejaneiro/mudamos-web#125]

**Comment by viniciusvgv** [comment]
segue o layout aprovado 
![image](https://cloud.githubusercontent.com/assets/7226070/22262263/587a79f0-e257-11e6-8e6f-62249ba5ccc7.png)

**Comment by viniciusvgv** [comment]
Segue o layout para quando o prazo de votação do projeto tiver encerrado
![image](https://cloud.githubusercontent.com/assets/7226070/22264665/f8dde58c-e25f-11e6-95f7-0d8092f5e493.png)
