### ISSUE TITLE
Criação do launch screen iOS

### ISSUE THREAD

**Issue by marcoamarelo** [itsriodejaneiro/mudamos-web#128]
Consultar @guimello sobre.

**Comment by reu** [comment]
Bom, a splash screen não tem muito segredo, mas de primeiro momento, o que acham?

![screen shot 2017-01-23 at 15 26 59](https://cloud.githubusercontent.com/assets/191614/22214872/6fbaa446-e180-11e6-84d3-5fa7aa27f9c6.png)

**Comment by marcoamarelo** [comment]
É isso @reu. Só me preocupa com estarmos abusando do roxo. Por outro lado, com isso geramos uma identidade maior com o ITS. Mas é isso. Fechado.
