### ISSUE TITLE
Gerar o ícone da App

### ISSUE THREAD

**Issue by marcoamarelo** [itsriodejaneiro/mudamos-web#129]
Usar o roxo do app no fundo da marca.

**Comment by reu** [comment]
![android-xxhdpi](https://cloud.githubusercontent.com/assets/191614/22215380/4ed6e526-e182-11e6-937c-899360aed185.png)

Algo assim?

**Comment by reu** [comment]
De qualquer forma, para adiantar, no zip abaixo já tem o ícone em todas as resoluções para o Android e iOS:
[Icons.zip](https://github.com/itsriodejaneiro/mudamos-web/files/724667/Icons.zip)

**Comment by marcoamarelo** [comment]
Isso @reu, acho que as linhas poderiam fechar mais do mais. @guimello com esse ajuste podemos usar.

**Comment by viniciusvgv** [comment]
Segue a versão final
![android-xxhdpi](https://cloud.githubusercontent.com/assets/7226070/22263201/c0d4ae3c-e25a-11e6-8422-f5558b362a59.png)
