### ISSUE TITLE
Criação de post em blog quebrado

### ISSUE THREAD

**Issue by marcoamarelo** [itsriodejaneiro/mudamos-web#210]
Retornando erro 500

ar 3 18:44:16 mudamos-staging app[web] info   Cycle Load (0.8ms)  SELECT  "cycles".* FROM "cycles" WHERE "cycles"."deleted_at" IS NULL AND "cycles"."id" = $1 LIMIT 1  [["id", 1]]
Mar 3 18:44:16 mudamos-staging app[web] info   Cycle Load (0.7ms)  SELECT  "cycles".* FROM "cycles" WHERE "cycles"."deleted_at" IS NULL AND "cycles"."id" = $1 LIMIT 1  [["id", 4]]
Mar 3 18:44:16 mudamos-staging app[web] info Completed 500 Internal Server Error in 22ms (ActiveRecord: 3.1ms)
Mar 3 18:44:16 mudamos-staging app[web] info 
Mar 3 18:44:16 mudamos-staging app[web] info NoMethodError (undefined method `name' for nil:NilClass):
Mar 3 18:44:16 mudamos-staging app[web] info   app/controllers/admin/blog_posts_controller.rb:70:in `block in set_plugin_relations'
Mar 3 18:44:16 mudamos-staging app[web] info   app/controllers/admin/blog_posts_controller.rb:70:in `set_plugin_relations'
Mar 3 18:44:16 mudamos-staging app[web] info 

http://testes.mudamos.org/admin/blog/new

**Comment by guimello** [comment]
O erro acontecia porque exista um `PluginRelation` apontando para um `Cycle` que não existia no banco.

Solução: Apagar do banco (soft delete) o `PluginRelation`

```
#<PluginRelation:0x007f1ceca32518
 id: 9,
 related_id: 4,
 related_type: "Cycle",
 plugin_id: 1,
 is_readonly: nil,
 read_only_at: nil,
 deleted_at: nil,
 created_at: Mon, 16 Jan 2017 17:18:39 BRST -02:00,
 updated_at: Mon, 16 Jan 2017 17:18:39 BRST -02:00,
 slug: "blog">
```

O porquê do ciclo (id=4) não estar no banco é um mistério. Alguém deve ter removido na mão.
