### ISSUE TITLE
App disponível na App Store de outros países

### ISSUE THREAD

**Issue by cuducos** [itsriodejaneiro/mudamos-web#353]
Sou brasileiro, mas, como morei na Inglaterra, minha conta na App Store é de lá. Resultado: não posso usar o Mudamos+.

![image](https://cloud.githubusercontent.com/assets/4732915/25265647/6fed5ac2-2644-11e7-9a9b-5208f03bf9cf.png)

Isso não é necessário, é?

**Comment by Irio** [comment]
Tenho o mesmo problema, mas a minha conta está nos EUA.

A Apple não permite baixar aplicativos de outras App Stores e nem fazer uma troca temporária. Dessa forma, a única possibilidade que tenho é retirar o meu cartão americano e colocar um brasileiro, com endereço local, para todas as minhas compras. https://support.apple.com/en-us/HT201389

**Comment by marcoamarelo** [comment]
Prezados @Irio e @cuducos o download estava restrito somente às lojas brasileiras no momento do seu lançamento. Com base no seu feedback, na sexta-feira liberamos o download em qualquer localidade. Obrigado.
