### ISSUE TITLE
Adicionar arquivo LICENSE para GPL3

### ISSUE THREAD

**Issue by cuducos** [itsriodejaneiro/mudamos-web#354]
Que tal um `LICENSE`? ; )

**Comment by marcoamarelo** [comment]
Obrigado @cuducos. Achávamos esse arquivo já estava na raiz do nosso repo. Isso já virou tarefa pra implementarmos ASAP.

**Comment by augusto-herrmann** [comment]
Por que não [GNU Affero GPL3](https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License)?

Essa é uma recomendação da Free Software Foundation para softwares que rodam em rede. Com a GPL3 original, alguém pode alterar o software e servi-lo como software somo serviço (SaaS) sem compartilhar o código fonte.
