### ISSUE TITLE
Margem pequena demais na lista de projetos

### ISSUE THREAD

**Issue by Irio** [itsriodejaneiro/mudamos-web#382]
Na listagem de projetos, o número de assinaturas aparece próximo demais da contagem regressiva para o término, dando a impressão que os dois números são na verdade um.

Note o espaçamento entre **113.995** e **77 dias** na imagem abaixo.

[<img src="https://user-images.githubusercontent.com/667753/27582647-4b86254e-5b3a-11e7-9cf8-fab22867401b.png" height="400" />](https://user-images.githubusercontent.com/667753/27582647-4b86254e-5b3a-11e7-9cf8-fab22867401b.png)

Quando clicamos no projeto, o espaçamento é maior (o tamanho da fonte parece ser também maior, o que ajuda na margem), não apresentando o mesmo problema.

[<img src="https://user-images.githubusercontent.com/667753/27582648-4b868872-5b3a-11e7-9138-e3cbdd8bbbd9.png" height="400" />](https://user-images.githubusercontent.com/667753/27582648-4b868872-5b3a-11e7-9138-e3cbdd8bbbd9.png)

O teste foi feito em um iPhone 5s.

**Comment by marcoamarelo** [comment]
Obrigado pela sua sugestão @Irio. Com base no seu feedback corrigimos isso na versão 1.5 do App. Por favor, atualize o seu App e verifique se a questão foi resolvida. Talvez o cache de aplicativo impeça a atualização, nessa caso sugiro você fazer um clear data.
