### ISSUE TITLE
Link quebrado: críticas e sugestões

### ISSUE THREAD

**Issue by dukejeffrie** [itsriodejaneiro/mudamos-web#418]
Como reproduzir o problema:

1. Acesse uma página de petição, por exemplo:
https://www.mudamos.org/temas/pela-transparencia-dos-partidos/plugins/peticao

2. Role a tela até o final

3. Clique no link "Críticas e sugestões". A página não existe.

Aparentemente o post que fala sobre a Ombudsman não existe mais.

**Comment by eduardozulian** [comment]
Opa. :) Na real ele existe: 

https://www.mudamos.org/blog/sobre-a-ombudsperson-silvia-ramos

Porém, o caminho correto para o link talvez não esteja sendo usado aqui: https://github.com/itsriodejaneiro/mudamos-web/blob/678213af4127c7ea499767657db58d949fa42a3a/app/views/layouts/shared/_footer.html.slim#L10
