### ISSUE TITLE
Remontar layout da apresentação da assinatura (layout mais próximo do aplicativo)

### ISSUE THREAD

**Issue by marcoamarelo** [itsriodejaneiro/mudamos-web#96]

**Comment by reu** [comment]
Segue a primeira versão das telas. Talvez ainda hajam algumas mudanças cosméticas, mas nada muito impactante.

### Telas superiores a 1024
A sidebar terá 50% do viewport, e os outros 50% serão a descrição da PLIP e o texto completo dela. Vale ressaltar que a ideia é manter o padding fixo em 50 pixels nas duas views.
![hd](https://cloud.githubusercontent.com/assets/191614/22157017/01c103e6-df1d-11e6-8897-37f845263a74.png)

### Telas inferiores a 1024 (tablets em geral)
O layout nesse caso muda consideravelmente, já que um menu lateral pegando metade da tela seria terrível nesse tamanho de tela.
![tablet](https://cloud.githubusercontent.com/assets/191614/22157029/0bff397c-df1d-11e6-8bf5-679843644c7a.png)

### Dispositivos mobile
Nos celulares a ideia é fazer algo muito semelhante a app
![mobile](https://cloud.githubusercontent.com/assets/191614/22157042/1aec4d26-df1d-11e6-8f48-d137f16ac88b.png)

**Comment by reu** [comment]
Ah sim, é importante lembrar que a cor principal é configurável via admin:

![blue](https://cloud.githubusercontent.com/assets/191614/22157569/588e9326-df1f-11e6-8494-4f421ebdfe3b.png)
![green](https://cloud.githubusercontent.com/assets/191614/22157570/588fcbba-df1f-11e6-9bb2-b64417e64a9b.png)

**Comment by reu** [comment]
Pessoal, segue uma ideia de como pode ser o fluxo quando o usuário clicar no botão para assinar a PLIP:
![hd](https://cloud.githubusercontent.com/assets/191614/22203998/de924ef2-e156-11e6-8326-86c5e9c8e443.png)

**Comment by marcoamarelo** [comment]
Oi @reu. O problema é que ao clicar, a pessoa tem que colocar pelo menos alguma informação para construirmos uma relação com eles. Acho que a mensagem está boa, mas não deve aparecer logo no click.
